### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by James858123** [KoczurekK/QSFML#4]
I tried to pull the code, but it produced an error message

```
Cloning into 'QSFML'...
remote: Enumerating objects: 932, done.
remote: Total 932 (delta 0), reused 0 (delta 0), pack-reused 932 eceiving objects:  91% (849/932), 1012.01 KiB | 100.00 Receiving objects: 100% (932/932), 1.07 MiB | 91.00 KiB/s, done.

Resolving deltas: 100% (537/537), done.
error: invalid path 'logo/qsfml-2:3.png'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

thank you very much for your help

**Comment by kamirr** [comment]
Ah, paths on Windows can't contain colons. This should be fixed now, try `git fetch` and `git checkout master` or just re-clone the entire repo.

BTW: I haven't touched this library for 4 years and some breaking changes might've been made in Qt 5 or SFML 2, hence it's possible that it doesn't work anymore. Feel free to submit another issue if that's the case, I'll see what I can do.

**Comment by James858123** [comment]
Thank you very much for your reply！
I can run successfully now，But I found a problem.
    I added this widget to my program as part of it, when the mouse clicks in this window, other areas will no longer respond to any click events. Do you have any solutions or ideas?

Looking forward for your response, thank you.

**Comment by James858123** [comment]
Add:
My program uses QSFML drawing, and there are some input boxes and buttons. Once the mouse clicks on the area where QSFML is located, other areas will not be able to get the focus (no operation can be performed). Until I click somewhere outside the application, then Click again on my app to enter.

Thank you very much for your help.

**Comment by kamirr** [comment]
That's interesting. Can you provide me with a code that reproduces this problem? Preferably a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

Also, please do so in a new GitHub issue - I'd like to keep stuff organized and close this one.

**Comment by James858123** [comment]
Sorry, I should have done this from the beginning, I will ask a new question and submit the test code
