### ISSUE TITLE
After clicking and dragging in the drawing area, other controls cannot get the focus

### ISSUE THREAD

**Issue by James858123** [KoczurekK/QSFML#5]
I tried using testwidget and then I found a problem，
This is my code，It's very simple

head file:
```
#include <QtWidgets/QMainWindow>
#include "ui_PotLine.h"

class TestQSFMLWidget : public QMainWindow
{
    Q_OBJECT

public:
	TestQSFMLWidget(QWidget *parent = Q_NULLPTR);

private slots:
	void OnClickBtn();

private:
	Ui::PotLineClass ui;
	class TestWidget * window = nullptr;
};
```

cpp file:
```
#include "TestQSFMLWidget.h"
#include "QPushButton"
#include "QSFML/testwidget.h"
#include "CDialog.h"
#include "QLineEdit"

TestQSFMLWidget::TestQSFMLWidget(QWidget *parent)
    : QMainWindow(parent)
{
	//  ui.setupUi(this);
	setFixedSize(QSize(1000, 1000));  

 	QWidget * wdt = new QWidget(this);
	wdt->setGeometry(0, 0, 400, 400);

 	window = new TestWidget(wdt, QPoint(0, 0), QSize(400, 400));

	QPushButton * btn = new QPushButton(this);
	btn->setGeometry(500,30,120, 30);
	btn->setText("showMessage");

	QLineEdit * edt = new QLineEdit(this);
	edt->setGeometry(500, 80, 120, 30);
	edt->setPlaceholderText("input something");
	
	connect(btn, &QPushButton::clicked, this, &TestQSFMLWidget::OnClickBtn);
}

void TestQSFMLWidget::OnClickBtn()
{
	CQDialog * dlg = new CQDialog();
	dlg->setModal(false);
	dlg->show();
}
```

And this is main function

```
int main(int argc, char *argv[])
{
	QApplication a(argc, argv);
	TestQSFMLWidget w;
	w.show();

	return a.exec();
}
```

This is the problem I found:

When I press and drag the mouse in TestWidget, the LineEdit and button will lose response.

It didn't return to normal until I clicked somewhere outside the program, and then returned to this program, but if I press the mouse and drag in the TestWidget, uh... it will repeat again

thank you very much for your help

**Comment by kamirr** [comment]
I don't think the code you supplied is complete, could you perhaps zip your entire project and attach it here?

I tried to reproduce the problem myself and modified the 'date' example to include a push button and a text field. I also added slots to both of them to see updates when the button is clicked, or when the content of the text field is modified. The QSFML widget also prints coordinates of each click inside of it. Those were the results:
![image](https://user-images.githubusercontent.com/7727537/86485082-15e01480-bd58-11ea-8210-a6d0da6f5524.png)
As you can see, I was able to interact with all widgets in an arbitrary order successfully.

I've attached my modified project ([date_modified.zip](https://github.com/kamirr/QSFML/files/4870546/date_modified.zip)). It would be nice if you could just run it without modifying it and see if it works for you - if it doesn't, it could mean that some of my code just doesn't work on Windows - I've only ever tested it on Linux.

**Comment by James858123** [comment]
Thank you very much for your help，Still the same result.

And I found the solution，Hide the widget when I release the mouse and then show it.
